# Generated by Django 4.1.4 on 2022-12-15 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_message_message_time_alter_message_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 15, 22, 58, 48, 930165)),
        ),
    ]
