# Generated by Django 4.1.4 on 2022-12-15 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_message_message_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomcode', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 15, 23, 16, 56, 303408)),
        ),
    ]
