# Generated by Django 4.1.4 on 2022-12-15 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_room_alter_message_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 15, 23, 32, 51, 634851)),
        ),
    ]
