# Generated by Django 4.1.4 on 2022-12-16 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_alter_message_content_alter_message_message_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 16, 12, 16, 30, 374836)),
        ),
    ]
